# Generated by Django 3.2.5 on 2022-02-15 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corporation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('howToDecideTheWinner', models.CharField(max_length=20)),
                ('bidRate', models.FloatField()),
                ('industryRestriction', models.CharField(max_length=100)),
                ('bidOrNot', models.CharField(max_length=2)),
                ('create_data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
